services:
  - type: web
    name: xarxanglesola
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_ALLOWED_ORIGINS
        sync: false
